theme = "onedark"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
[keys.insert]
C-p = "move_line_up"
C-n = "move_line_down"
C-e = "goto_line_end_newline"
C-a = "goto_line_start"
C-f = "move_char_right"
C-b = "move_char_left"

[keys.normal]
L = ["ensure_selections_forward", "extend_to_line_end"]
#H = ["ensure_selections_backward", "extend_to_line_start"]
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]
